name: orw-1
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.20=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.4=hd7fb8db_0
  - ipykernel=7.2.0=pyh6dadd2b_1
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py311haa95532_1
  - parso=0.8.6=pyhcf101f3_0
  - pip=26.0.1=pyhc872135_0
  - platformdirs=4.9.2=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pywin32=311=py311hefeebc8_1
  - pyzmq=27.1.0=py311hb77b9c8_0
  - setuptools=80.10.2=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py311h3485c13_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - wheel=0.46.3=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.61.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - numpy==2.4.2
      - openpyxl==3.1.5
      - pandas==3.0.1
      - pillow==12.1.1
      - pyparsing==3.3.2
      - pyxlsb==1.0.10
      - seaborn==0.13.2
      - tzdata==2025.3
prefix: C:\Users\U2\miniconda3\envs\orw-1
